/*
 * Hola Mundo
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.agenciaalquiler1.vista;

import com.mycompany.agenciaalquiler1.controlador.Controlador;
import com.mycompany.agenciaalquiler1.dao.DaoException;
import com.mycompany.agenciaalquiler1.modelo.Grupo;
import com.mycompany.agenciaalquiler1.modelo.Vehiculo;
import java.io.File;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author veronique.gru
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
       //Properties propiedaddes = new Properties();
       // try(BufferedReader fichero=Files.newBufferedReader(Paths.get(uri)))
        setTitle("Agencia de alquier de vehículos");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgOrdenLista = new javax.swing.ButtonGroup();
        selectorFicheros = new javax.swing.JFileChooser(new File("."));
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlPlazas = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnVehiculoMasBarato = new javax.swing.JButton();
        btnVehiculoMasCaro = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        tfMatricula = new javax.swing.JTextField();
        cbGrupo = new javax.swing.JComboBox<>();
        cbTipo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jSpinnerPlazas = new javax.swing.JSpinner();
        jlCapacidad = new javax.swing.JLabel();
        jfCapacidad = new javax.swing.JFormattedTextField();
        jFtPrecioDia = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbListaVehiculos = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        rbMatricula = new javax.swing.JRadioButton();
        rbPrecioAlq = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbFiltroGrupo = new javax.swing.JComboBox<>();
        cbFiltroTipo = new javax.swing.JComboBox<>();
        btnListarVehiculos = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAbrir = new javax.swing.JMenu();
        jMIAbrir = new javax.swing.JMenuItem();
        jMIGuardar = new javax.swing.JMenuItem();
        menuNuevo = new javax.swing.JMenu();
        jMINuevo = new javax.swing.JMenuItem();
        jMIBuscar = new javax.swing.JMenuItem();
        jMExamen = new javax.swing.JMenu();
        jMEjercicio1 = new javax.swing.JMenuItem();
        Ejercicio2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/mycompany/agenciaalquiler1/vista/Bundle"); // NOI18N
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("Ventana.jPanel1.border.title"))); // NOI18N

        jLabel1.setText(bundle.getString("Ventana.jLabel1.text")); // NOI18N

        jLabel2.setText(bundle.getString("Ventana.jLabel2.text")); // NOI18N

        jlPlazas.setText(bundle.getString("Ventana.jlPlazas.text")); // NOI18N

        jLabel4.setText(bundle.getString("Ventana.jLabel4.text")); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("Ventana.jPanel3.border.title"))); // NOI18N

        btnVehiculoMasBarato.setText(bundle.getString("Ventana.btnVehiculoMasBarato.text")); // NOI18N
        btnVehiculoMasBarato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehiculoMasBaratoActionPerformed(evt);
            }
        });

        btnVehiculoMasCaro.setText(bundle.getString("Ventana.btnVehiculoMasCaro.text")); // NOI18N
        btnVehiculoMasCaro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehiculoMasCaroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnVehiculoMasBarato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVehiculoMasCaro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(btnVehiculoMasBarato)
                .addGap(31, 31, 31)
                .addComponent(btnVehiculoMasCaro)
                .addGap(42, 42, 42))
        );

        btnBorrar.setText(bundle.getString("Ventana.btnBorrar.text")); // NOI18N
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnModificar.setText(bundle.getString("Ventana.btnModificar.text")); // NOI18N
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        tfMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMatriculaActionPerformed(evt);
            }
        });

        cbGrupo.setEditable(true);
        cbGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C" }));
        cbGrupo.setEnabled(false);
        cbGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGrupoActionPerformed(evt);
            }
        });

        cbTipo.setEditable(true);
        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TURISMO", "FURGONETA" }));
        cbTipo.setEnabled(false);
        cbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoActionPerformed(evt);
            }
        });

        jLabel8.setText(bundle.getString("Ventana.jLabel8.text")); // NOI18N

        jlCapacidad.setText(bundle.getString("Ventana.jlCapacidad.text")); // NOI18N

        jfCapacidad.setValue(0.0f);
        jfCapacidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfCapacidadActionPerformed(evt);
            }
        });

        jFtPrecioDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFtPrecioDiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnBorrar)
                                .addGap(73, 73, 73)
                                .addComponent(btnModificar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(35, 35, 35)
                                .addComponent(jFtPrecioDia, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(45, 45, 45)
                                .addComponent(tfMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jlPlazas)
                                        .addGap(51, 51, 51)
                                        .addComponent(jSpinnerPlazas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(51, 51, 51)
                                        .addComponent(jLabel8)))
                                .addGap(18, 18, 18)
                                .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlCapacidad)
                                .addGap(27, 27, 27)
                                .addComponent(jfCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPlazas)
                    .addComponent(jSpinnerPlazas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCapacidad)
                    .addComponent(jfCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jFtPrecioDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBorrar)
                    .addComponent(btnModificar))
                .addGap(52, 52, 52)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("Ventana.jPanel2.border.title"))); // NOI18N

        vtm=new VehiculoTableModel();
        tbListaVehiculos.setModel(vtm);
        tbListaVehiculos.getSelectionModel().addListSelectionListener(new ListSelectionListener(){public void valueChanged(ListSelectionEvent lse){
            int fila=tbListaVehiculos.getSelectedRow();
            if(fila>=0){
                mostrarMatricula((String)tbListaVehiculos.getValueAt(fila, 0));
                //mostrarTipo((Integer)tbListaVehiculos.getValueAt(fila, 1)==0?"TURISMO":"FURGONETA");
                mostrarTipo((String) tbListaVehiculos.getValueAt(fila, 1));
                mostrarGrupo((String)tbListaVehiculos.getValueAt(fila, 2));
                // mostrarGrupo((String)tbListaVehiculos.getValueAt(fila, 2));
                mostrarPlazas((Integer)tbListaVehiculos.getValueAt(fila, 3));
                mostrarCapacidad((Float)tbListaVehiculos.getValueAt(fila, 4));
                mostrarPrecioAlquiler((Float)tbListaVehiculos.getValueAt(fila, 5));
            }
        }});
        tbListaVehiculos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbListaVehiculos);

        jLabel5.setText(bundle.getString("Ventana.jLabel5.text")); // NOI18N

        bgOrdenLista.add(rbMatricula);
        rbMatricula.setSelected(true);
        rbMatricula.setText(bundle.getString("Ventana.rbMatricula.text")); // NOI18N
        rbMatricula.setActionCommand(bundle.getString("Ventana.rbMatricula.actionCommand")); // NOI18N
        rbMatricula.setActionCommand("MATRÍCULA");
        rbMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMatriculaActionPerformed(evt);
            }
        });

        bgOrdenLista.add(rbPrecioAlq);
        rbPrecioAlq.setText("PRECIO ALQUILER");
        rbPrecioAlq.setActionCommand(bundle.getString("Ventana.rbPrecioAlq.actionCommand")); // NOI18N
        rbPrecioAlq.setActionCommand("PRECIO ALQUILER");

        jLabel6.setText(bundle.getString("Ventana.jLabel6.text")); // NOI18N

        jLabel7.setText(bundle.getString("Ventana.jLabel7.text")); // NOI18N

        cbFiltroGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS", "A", "B", "C", " " }));
        cbFiltroGrupo.setActionCommand(bundle.getString("Ventana.cbFiltroGrupo.actionCommand")); // NOI18N
        cbFiltroGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFiltroGrupoActionPerformed(evt);
            }
        });

        cbFiltroTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS", "TURISMO", "FURGONETA" }));
        cbFiltroTipo.setActionCommand(bundle.getString("Ventana.cbFiltroTipo.actionCommand")); // NOI18N
        cbFiltroTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFiltroTipoActionPerformed(evt);
            }
        });

        btnListarVehiculos.setText(bundle.getString("Ventana.btnListarVehiculos.text")); // NOI18N
        btnListarVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarVehiculosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rbMatricula)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(rbPrecioAlq))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(73, 73, 73)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbFiltroGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbFiltroTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 145, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnListarVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(275, 275, 275))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnListarVehiculos)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(cbFiltroGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbFiltroTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbPrecioAlq)
                    .addComponent(rbMatricula))
                .addGap(23, 23, 23))
        );

        menuAbrir.setText(bundle.getString("Ventana.menuAbrir.text")); // NOI18N

        jMIAbrir.setText(bundle.getString("Ventana.jMIAbrir.text")); // NOI18N
        jMIAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIAbrirActionPerformed(evt);
            }
        });
        menuAbrir.add(jMIAbrir);

        jMIGuardar.setText(bundle.getString("Ventana.jMIGuardar.text")); // NOI18N
        jMIGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIGuardarActionPerformed(evt);
            }
        });
        menuAbrir.add(jMIGuardar);

        jMenuBar1.add(menuAbrir);

        menuNuevo.setText(bundle.getString("Ventana.menuNuevo.text")); // NOI18N

        jMINuevo.setText(bundle.getString("Ventana.jMINuevo.text")); // NOI18N
        jMINuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMINuevoActionPerformed(evt);
            }
        });
        menuNuevo.add(jMINuevo);

        jMIBuscar.setText(bundle.getString("Ventana.jMIBuscar.text")); // NOI18N
        jMIBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIBuscarActionPerformed(evt);
            }
        });
        menuNuevo.add(jMIBuscar);

        jMenuBar1.add(menuNuevo);

        jMExamen.setText(bundle.getString("Ventana.jMExamen.text")); // NOI18N

        jMEjercicio1.setText(bundle.getString("Ventana.jMEjercicio1.text")); // NOI18N
        jMEjercicio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMEjercicio1ActionPerformed(evt);
            }
        });
        jMExamen.add(jMEjercicio1);

        Ejercicio2.setText(bundle.getString("Ventana.Ejercicio2.text")); // NOI18N
        Ejercicio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ejercicio2ActionPerformed(evt);
            }
        });
        jMExamen.add(Ejercicio2);

        jMenuBar1.add(jMExamen);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMatriculaActionPerformed

    private void cbGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGrupoActionPerformed
        
    }//GEN-LAST:event_cbGrupoActionPerformed

    private void cbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoActionPerformed
       if(cbTipo.getSelectedIndex()==0){
           this.jlPlazas.setVisible(true);
            this.jSpinnerPlazas.setVisible(true);
            this.jlCapacidad.setVisible(false);
            this.jfCapacidad.setVisible(false);
        }else{
           this.jlPlazas.setVisible(false);
            this.jSpinnerPlazas.setVisible(false);
            this.jlCapacidad.setVisible(true);
            this.jfCapacidad.setVisible(true);
       }
    }//GEN-LAST:event_cbTipoActionPerformed

    private void jfCapacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfCapacidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfCapacidadActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        if(!getMatricula().isBlank()){
            controlador.eliminarVehiculo();
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        
            controlador.modificarVehiculo();
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnVehiculoMasBaratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehiculoMasBaratoActionPerformed
        controlador.buscarVehiculoMasBarato();// TODO add your handling code here:
    }//GEN-LAST:event_btnVehiculoMasBaratoActionPerformed

    private void btnVehiculoMasCaroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehiculoMasCaroActionPerformed
        controlador.buscarVehiculoMasCaro();
    }//GEN-LAST:event_btnVehiculoMasCaroActionPerformed

    private void rbMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMatriculaActionPerformed

    private void cbFiltroGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFiltroGrupoActionPerformed
       // controlador.listarVehiculosGrupo();
    }//GEN-LAST:event_cbFiltroGrupoActionPerformed

    private void jFtPrecioDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFtPrecioDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFtPrecioDiaActionPerformed

    private void cbFiltroTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFiltroTipoActionPerformed
       // controlador.listarVehiculosTipo();
    }//GEN-LAST:event_cbFiltroTipoActionPerformed

    private void btnListarVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarVehiculosActionPerformed
      controlador.listarVehiculos();
    }//GEN-LAST:event_btnListarVehiculosActionPerformed

    private void jMIBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIBuscarActionPerformed
          String matricula=JOptionPane.showInputDialog(this,"Vehiculo a buscar:");
        if(matricula!=null){
            limpiarCampos();
            mostrarMatricula(matricula);
            controlador.buscarVehiculo();
        }
    }//GEN-LAST:event_jMIBuscarActionPerformed

    private void jMINuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMINuevoActionPerformed
       if(dialogoVehiculo.mostrar()==DialogoVehiculo.ACEPTAR){
           
            mostrarMatricula(dialogoVehiculo.getMatricula());
            mostrarTipo(dialogoVehiculo.getTipo());
            mostrarGrupo(dialogoVehiculo.getGrupo());
            mostrarPlazas(dialogoVehiculo.getPlazas());
            mostrarCapacidad(dialogoVehiculo.getCapacidad());
            
            controlador.crearVehiculo();
        }
    }//GEN-LAST:event_jMINuevoActionPerformed

    private void jMIAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAbrirActionPerformed
          if (selectorFicheros.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
           try {
                controlador.cargarVehiculos();
            } catch (DaoException ex) {
                Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jMIAbrirActionPerformed

    private void jMIGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIGuardarActionPerformed
        if (selectorFicheros.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            controlador.guardarVehiculos();
        }
    }//GEN-LAST:event_jMIGuardarActionPerformed

    private void jMEjercicio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMEjercicio1ActionPerformed
       controlador.exercicio1();
    }//GEN-LAST:event_jMEjercicio1ActionPerformed

    private void Ejercicio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ejercicio2ActionPerformed
       controlador.exercicio2();
    }//GEN-LAST:event_Ejercicio2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }
    public String getMatricula(){
      return this.tfMatricula.getText();
    }
    public String getGrupo(){
        return (String)this.cbGrupo.getSelectedItem();
    }
    public int getPlazas(){
        return (Integer)this.jSpinnerPlazas.getValue();
    }
    public String getTipo(){
        return (String)this.cbTipo.getSelectedItem();
    }
    public float getCapacidad(){
        return Float.parseFloat(this.jfCapacidad.getValue().toString());
    }
    public String getArchivo(){
        return this.selectorFicheros.getSelectedFile().getAbsolutePath();
    }
    public String getOrden(){
        return this.bgOrdenLista.getSelection().getActionCommand();
    }
    public String getFiltroGrupo(){
        return (String)this.cbFiltroGrupo.getSelectedItem();
    }
    public String getFlitroTipo(){
        return (String)this.cbFiltroTipo.getSelectedItem();
    }
    public void mostrarMatricula(String matricula){
        this.tfMatricula.setText(matricula);
    }
    public void mostrarTipo(String tipo){
        this.cbTipo.setSelectedItem(tipo);
    }
    public void mostrarGrupo(String grupo){
       //Grupo grupo = Grupo.valueOf(grupoString.toUpperCase());
      //this.cbGrupo.setSelectedItem(grupo);
      this.cbGrupo.setSelectedItem(grupo);
        //this.cbGrupo.setSelectedItem(Grupo.valueOf(grupo));
        //this.cbGrupo.setSelectedItem(Arrays.toString(Grupo.values()));
    }
   /* public void mostrarGrupo(String grupoStr) {
    try {
        Grupo grupo = Grupo.valueOf(grupoStr.toUpperCase());
        this.cbGrupo.setSelectedItem(grupo);
    } catch (IllegalArgumentException e) {
        // Manejar error si el string no corresponde a un valor de enum
        System.err.println("Grupo no válido: " + grupoStr);
    }
}*/
    public void mostrarPlazas(int plazas){
        this.jSpinnerPlazas.setValue(plazas);
    }
    public void mostrarCapacidad(Float capacidad){
        this.jfCapacidad.setValue(capacidad != null ? capacidad : 0f);
    }
    public void mostrarPrecioAlquiler(Float precio){
        this.jFtPrecioDia.setValue(precio != null ? precio : 0f);
    }
    public void listarVehiculos(List<Vehiculo> listadoVehiculo){
           vtm.setListadoVehiculo(listadoVehiculo);
    }
    public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }
     public boolean solicitarConfirmacion() {
        return JOptionPane.showConfirmDialog(this, "¿Seguro?") == JOptionPane.YES_OPTION;
    }

    public void setControlador(Controlador controlador) {
        this.controlador = controlador;
    }
     public String getEntradaExamen(String mensaje){
        return JOptionPane.showInputDialog(mensaje);
    }
    public void limpiarCampos(){
        this.tfMatricula.setText("");
        this.cbGrupo.setSelectedItem("A");
        this.cbTipo.setSelectedItem("TURISMO");
        this.jSpinnerPlazas.setValue(0);
        this.jFtPrecioDia.setValue(0);
    }
    

    public void mostrar() {
        setVisible(true);
    }
    public void actualizarTabla(){
      
        controlador.listarVehiculos();
      
    }
    
    public final static int SI=0;
    private Controlador controlador;
    private DialogoVehiculo dialogoVehiculo=new DialogoVehiculo(this,true);

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Ejercicio2;
    private javax.swing.ButtonGroup bgOrdenLista;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnListarVehiculos;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnVehiculoMasBarato;
    private javax.swing.JButton btnVehiculoMasCaro;
    private javax.swing.JComboBox<String> cbFiltroGrupo;
    private javax.swing.JComboBox<String> cbFiltroTipo;
    private javax.swing.JComboBox<String> cbGrupo;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JFormattedTextField jFtPrecioDia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuItem jMEjercicio1;
    private javax.swing.JMenu jMExamen;
    private javax.swing.JMenuItem jMIAbrir;
    private javax.swing.JMenuItem jMIBuscar;
    private javax.swing.JMenuItem jMIGuardar;
    private javax.swing.JMenuItem jMINuevo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerPlazas;
    private javax.swing.JFormattedTextField jfCapacidad;
    private javax.swing.JLabel jlCapacidad;
    private javax.swing.JLabel jlPlazas;
    private javax.swing.JMenu menuAbrir;
    private javax.swing.JMenu menuNuevo;
    private javax.swing.JRadioButton rbMatricula;
    private javax.swing.JRadioButton rbPrecioAlq;
    private javax.swing.JFileChooser selectorFicheros;
    private VehiculoTableModel vtm;
    private javax.swing.JTable tbListaVehiculos;
    private javax.swing.JTextField tfMatricula;
    // End of variables declaration//GEN-END:variables

    
}
