
# Hola Mundo
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template

.level= INFO
#nivel en el que empieza
handlers= java.util.logging.FileHandler
java.util.logging.FileHandler.formatter = java.util.logging.SimpleFormatter
#formato simple
java.util.logging.FileHandler.encoding = UTF-8
java.util.logging.FileHandler.append = true
#si quiero que a cada vez que se runeae al aopp que se siga escribiendo
java.util.logging.FileHandler.pattern = registroExamen.log